server:
  port: 80
  tomcat:
    uri-encoding: utf-8
    basedir: /springboot-tomcat-tmp
  
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/learn_springboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    initialSize: 2
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  level:
    root: info
    org.mybatis: info
    com.cabin: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpth:mappers/**/*.xml

